# Setup
title:            Sistemas discretos
tagline:          'LIMA, UAEH, 2017'
description:      'LIMA, UAEH, 2017'
url:              "http://rvf0068.github.com/discretos"
baseurl:          "/discretos"

author:
  name:           'Rafael Villarroel'
  url:            https://twitter.com/rvf0068

paginate:         5

# Custom vars
github:
  repo:           https://github.com/rvf0068/discretos

plugins:          [jekyll-paginate]

language:         spanish

disqus:           mateclases.disqus.com/embed.js

# see https://github.com/github/pages-gem/issues/399#issuecomment-301827749
github:           [metadata]