# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Geometría
tagline:          'LIMA, UAEH, 2016'
description:      'LIMA, UAEH, 2016'
url:              "http://rvf0068.gmail.com/my-hyde"
baseurl:          "/my-hyde"

author:
  name:           'Rafael Villarroel'
  url:            https://twitter.com/rvf0068

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rvf0068/my-hyde

gems:             [jekyll-paginate]