# Setup
title:            Introducción a la teoría de gráficas
tagline:          'LIMA, UAEH, 2019'
description:      'LIMA, UAEH, 2019'
url:              "http://rvf0068.github.com/graficas"
baseurl:          "/graficas"

author:
  name:           'Rafael Villarroel'
  url:            https://twitter.com/rvf0068

paginate:         5

# Custom vars
github:
  repo:           https://github.com/rvf0068/graficas

plugins:          [jekyll-paginate]

language:         spanish

disqus:           mateclases.disqus.com/embed.js

# see https://github.com/github/pages-gem/issues/399#issuecomment-301827749
github:           [metadata]